

export const FETCH_MENS_DATA_REQUEST = "FETCH_MENS_DATA_REQUEST";
export const FETCH_MENS_DATA_SUCCESS = "FETCH_MENS_DATA_SUCCESS";
export const FETCH_MENS_DATA_FAILURE = "FETCH_MENS_DATA_FAILLURE";

export const SINGLE_MENS_DATA_REQUEST = "SINGLE_MENS_DATA_REQUEST";
export const SINGLE_MENS_DATA_SUCCESS = "SINGLE_MENS_DATA_SUCCESS";
export const SINGLE_MENS_DATA_FAILURE = "SINGLE_MENS_DATA_FAILLURE";

export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILLURE";
