

export const FETCH_MENS_DATA_REQUEST = "FETCH_MENS_DATA_REQUEST";
export const FETCH_MENS_DATA_SUCCESS = "FETCH_MENS_DATA_SUCCESS";
export const FETCH_MENS_DATA_FAILURE = "FETCH_MENS_DATA_FAILLURE";